#!/bin/bash

cd "$(dirname "$0")"
tag=yt-subs
docker build -t "$tag" .
docker stop "$tag"
docker rm "$tag"
docker run --name "$tag"     \
  -v "$(pwd)/data":/app/data \
  -p 127.0.0.1:3002:3000     \
  -d                         \
  --restart unless-stopped   \
  "$tag:latest"
